FROM jupyter/base-notebook
ENV CONF_JU=/etc/jupyter/jupyter_notebook_config.py
USER root
#
#RUN echo "\\nc.NotebookApp.allow_origin = '*'" >> $CONF_JU; \
#    echo "\\nc.NotebookApp.password = $JU_PASSWORD" >>$CONF_JU; \
#    echo "c.NotebookApp.notebook_dir = '$NOTEBOOK_HOME'" >> $CONF_JU;

